language: node_js
node_js:
- stable
after_success:
- npm run coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_8ef018dbaa66_key -iv $encrypted_8ef018dbaa66_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
before_deploy:
- rm -rf node_modules
- zip -r paldalvalley-server .
- mkdir -p deploy
- mv paldalvalley-server.zip deploy/paldalvalley-server.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: paldalvalley-ci-cd
  region: ap-northeast-2
  skip_cleanup: true
  local_dir: deploy
  wait-until-deployed: true
  on:
    repo: paldal-valley/api
    branch: master
  dot_match: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: paldalvalley-ci-cd
  key: paldalvalley-server.zip
  bundle_type: zip
  application: paldalvalley-ci-cd-codeDeploy-service
  deployment_group: paldalvalley-api-deploy
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: paldal-valley/api
    branch: master
notifications:
  email:
    recipients:
    - qwaserdf@ajou.ac.kr
    - makehoney3@gmail.com
