#!/bin/sh

ssh ubuntu@15.164.49.56 <<EOF
    cd ~/api
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF